name: Terraform Deployment

on:
  push:
    branches:
      - master

jobs:
  step2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        
      - name: Decode Google Credentials
        run: |
          echo "${{ secrets.GOOGLE_CREDENTIALS_B64 }}" | base64 -d > $HOME/credentials.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=$HOME/credentials.json" >> $GITHUB_ENV

      - name: Terraform Init (Step 2)
        run: terraform init
        working-directory: ./step2

      - name: Terraform Plan (Step 2)
        id: check_plan_step2
        run: |
          terraform plan -out=tfplan -var="ssh_public_key=${{ secrets.SSH_PUBLIC_KEY }}"
          exit_code=$?
          echo "exit_code=$exit_code" >> $GITHUB_ENV
          echo "::set-output name=plan_exit_code::$exit_code"
        working-directory: ./step2

      - name: Terraform Apply (Step 2)
        if: ${{ steps.check_plan_step2.outputs.plan_exit_code == '2' }}
        run: terraform apply -auto-approve -var="ssh_public_key=${{ secrets.SSH_PUBLIC_KEY }}"
        working-directory: ./step2

      - name: Terraform Skip Apply (Step 2)
        if: ${{ steps.check_plan_step2.outputs.plan_exit_code == '0' }}
        run: echo "Resources already exist, skipping apply."
        working-directory: ./step2

      - name: Terraform Destroy (Step 2)
        if: failure()
        run: terraform destroy -auto-approve -var="ssh_public_key=${{ secrets.SSH_PUBLIC_KEY }}"
        working-directory: ./step2

  step3:
    runs-on: ubuntu-latest
    needs: step2  

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Decode Google Credentials
        run: |
          echo "${{ secrets.GOOGLE_CREDENTIALS_B64 }}" | base64 -d > $HOME/credentials.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=$HOME/credentials.json" >> $GITHUB_ENV

      - name: Terraform Init (Step 3)
        run: terraform init
        working-directory: ./step3

      - name: Terraform Plan (Step 3)
        id: check_plan_step3
        run: |
          terraform plan -out=tfplan -var="ssh_public_key=${{ secrets.SSH_PUBLIC_KEY }}"
          exit_code=$?
          echo "exit_code=$exit_code" >> $GITHUB_ENV
          echo "::set-output name=plan_exit_code::$exit_code"
        working-directory: ./step3

      - name: Terraform Apply (Step 3)
        if: ${{ steps.check_plan_step3.outputs.plan_exit_code == '2' }}
        run: terraform apply -auto-approve -var="ssh_public_key=${{ secrets.SSH_PUBLIC_KEY }}"
        working-directory: ./step3

      - name: Terraform Skip Apply (Step 3)
        if: ${{ steps.check_plan_step3.outputs.plan_exit_code == '0' }}
        run: echo "Resources already exist, skipping apply."
        working-directory: ./step3

      - name: Terraform Destroy (Step 3)
        if: failure()
        run: terraform destroy -auto-approve -var="ssh_public_key=${{ secrets.SSH_PUBLIC_KEY }}"
        working-directory: ./step3

  cleanup:
    runs-on: ubuntu-latest
    needs: [step2, step3]  

    steps:
      - name: Securely Cleanup Credentials
        if: always()
        run: shred -u $HOME/credentials.json
